<%@ Page Title="" Language="C#" MasterPageFile="~/SMS.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="Student_Management_System.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="text-align:center;">
    <h1>This is admin page........!</h1>
    <hr style="height: 2px; width: 1757px" />
    <asp:DropDownList ID="DropDownList1" runat="server" style="margin-left: 298px" Width="136px">
        <asp:ListItem>Coursetable</asp:ListItem>
        <asp:ListItem>student</asp:ListItem>
        <asp:ListItem>tutor</asp:ListItem>
        </asp:DropDownList>
    <asp:Button ID="ButSubmit" runat="server" Text="Submit" style="margin-left: 45px" Width="170px" />
    <asp:GridView ID="GdCourse" runat="server" DataKeyNames="Cid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdCourse_RowCancelingEdit" OnRowDeleting="GdCourse_RowDeleting" OnRowEditing="GdCourse_RowEditing" OnRowUpdating="GdCourse_RowUpdating" style="margin-left: 221px" Width="910px"></asp:GridView>
    <asp:GridView ID="GdStudent" runat="server" DataKeyNames="Stid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdStudent_RowCancelingEdit" OnRowDeleting="GdStudent_RowDeleting" OnRowEditing="GdStudent_RowEditing" OnRowUpdating="GdStudent_RowUpdating" style="margin-left: 226px" Width="904px"></asp:GridView>
    <asp:GridView ID="GdTutor" runat="server" DataKeyNames="Tid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdTutor_RowCancelingEdit" OnRowDeleting="GdTutor_RowDeleting" OnRowEditing="GdTutor_RowEditing" OnRowUpdating="GdTutor_RowUpdating" style="margin-left: 233px" Width="895px"></asp:GridView>
        </div>
</asp:Content>
